--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LeoWasCoding/TradeUI
branches:
- main
projects:
  TradeUI:
    path: ""
    libs:
      - src: Muqsit/invmenu/InvMenu
        branch: pm5
        version: ^4.6.5
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
