--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LeoWasCoding/TradeUI
build-by-default: true
branches:
- main
projects:
  TradeUI:
    path: ""
    libs:
      - src: muqsit/InvMenu
        branch: pm5
        version: ^4.6.3
...
