name: TradeUI
version: 2.0.0
main: leowascoding\tradeui\TradeUI
api: 5.3.0
commands:
  trade:
    description: Request a trade with a nearby player
    usage: /trade <player>
    permission: tradeui.command
permissions:
  tradeui.command:
    default: true
