# ┌────────────────────────────────────────────────────────────┐
# │                     TradeUI Settings                        │
# └────────────────────────────────────────────────────────────┘
#
# Configuration parameters for trading mechanics:
#
# trade-radius:
#   - The maximum distance (in blocks) allowed between two players 
#     when sending or accepting a trade request.
#   - Players further apart than this radius cannot trade.
#
# request-timeout:
#   - Duration (in seconds) that a trade request stays pending.
#   - If not accepted or denied within this time, the request expires automatically.
#
# trade-timeout:
#   - Duration (in seconds) a started trade session may last.
#   - If the trade isn't completed within this time, it cancels automatically.
# allowed-worlds:
#   - A list of world names where trading commands are permitted.
#   - Players can only initiate or respond to trades in these worlds.
#   - Leave empty or set to [] to allow trading in all worlds.

trade-radius: 10.0

request-timeout: 30

trade-timeout: 30

# Leave empty or set to [] to allow trading in all worlds.
allowed-worlds: []

# Example with multiple worlds:
# allowed-worlds:
#   - "world"
#   - "world_nether"
